project:
  type: website

website:
  title: "Mariana Gomes | Consultoria Estatística"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: servicos.qmd
        text: Serviços
      - href: contato.qmd
        text: Contato
      - href: blog.qmd
        text: Blog
  page-footer: "© 2025 Mariana Gomes | Consultoria Estatística"
format:
  html:
    theme: minty
    toc: true

